<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="5" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="com.Pcitc.AppAutomationTest.pagesHelper.TestInit" duration-ms="63276" started-at="2017-02-18T10:45:53Z" finished-at="2017-02-18T10:46:56Z">
    <groups>
    </groups>
    <test name="com.Pcitc.AppAutomationTest.pagesHelper.TestInit" duration-ms="63276" started-at="2017-02-18T10:45:53Z" finished-at="2017-02-18T10:46:56Z">
      <class name="com.Pcitc.AppAutomationTest.testCases.DengLuTest">
        <test-method status="PASS" signature="getPageElement()[pri:0, instance:com.Pcitc.AppAutomationTest.testCases.DengLuTest@73846619]" name="getPageElement" is-config="true" duration-ms="41632" started-at="2017-02-18T18:46:13Z" finished-at="2017-02-18T18:46:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPageElement -->
        <test-method status="FAIL" signature="rightLogin()[pri:0, instance:com.Pcitc.AppAutomationTest.testCases.DengLuTest@73846619]" name="rightLogin" duration-ms="24" started-at="2017-02-18T18:46:55Z" description="正确用户名密码" finished-at="2017-02-18T18:46:55Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.Pcitc.AppAutomationTest.utils.Action.sendKey(Action.java:278)
	at com.Pcitc.AppAutomationTest.testCases.DengLuTest.rightLogin(DengLuTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rightLogin -->
        <test-method status="FAIL" signature="BiguserLogin()[pri:0, instance:com.Pcitc.AppAutomationTest.testCases.DengLuTest@73846619]" name="BiguserLogin" duration-ms="21" started-at="2017-02-18T18:46:55Z" description="用户名大写" finished-at="2017-02-18T18:46:55Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.Pcitc.AppAutomationTest.utils.Action.sendKey(Action.java:278)
	at com.Pcitc.AppAutomationTest.testCases.DengLuTest.BiguserLogin(DengLuTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BiguserLogin -->
        <test-method status="FAIL" signature="wrongUserLogin()[pri:0, instance:com.Pcitc.AppAutomationTest.testCases.DengLuTest@73846619]" name="wrongUserLogin" duration-ms="19" started-at="2017-02-18T18:46:55Z" description="密码大写" finished-at="2017-02-18T18:46:55Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.Pcitc.AppAutomationTest.utils.Action.sendKey(Action.java:278)
	at com.Pcitc.AppAutomationTest.testCases.DengLuTest.wrongUserLogin(DengLuTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrongUserLogin -->
        <test-method status="FAIL" signature="wrongPasswordLogin()[pri:0, instance:com.Pcitc.AppAutomationTest.testCases.DengLuTest@73846619]" name="wrongPasswordLogin" duration-ms="4" started-at="2017-02-18T18:46:55Z" description="用户名为空" finished-at="2017-02-18T18:46:55Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.Pcitc.AppAutomationTest.utils.Action.tap(Action.java:264)
	at com.Pcitc.AppAutomationTest.utils.Action.clearInputTextbox(Action.java:91)
	at com.Pcitc.AppAutomationTest.testCases.DengLuTest.wrongPasswordLogin(DengLuTest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrongPasswordLogin -->
      </class> <!-- com.Pcitc.AppAutomationTest.testCases.DengLuTest -->
      <class name="com.Pcitc.AppAutomationTest.pagesHelper.TestInit">
        <test-method status="PASS" signature="AppPlatform(java.lang.Boolean, java.lang.Boolean)[pri:0, instance:com.Pcitc.AppAutomationTest.pagesHelper.TestInit@6e06451e]" name="AppPlatform" is-config="true" duration-ms="88" started-at="2017-02-18T18:45:52Z" description="获得平台类型" finished-at="2017-02-18T18:45:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AppPlatform -->
        <test-method status="PASS" signature="getAppiumDriver()[pri:0, instance:com.Pcitc.AppAutomationTest.pagesHelper.TestInit@6e06451e]" name="getAppiumDriver" is-config="true" duration-ms="20292" started-at="2017-02-18T18:45:53Z" finished-at="2017-02-18T18:46:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAppiumDriver -->
        <test-method status="PASS" signature="autoTest()[pri:0, instance:com.Pcitc.AppAutomationTest.pagesHelper.TestInit@6e06451e]" name="autoTest" duration-ms="9" started-at="2017-02-18T18:46:13Z" finished-at="2017-02-18T18:46:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- autoTest -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:com.Pcitc.AppAutomationTest.pagesHelper.TestInit@6e06451e]" name="closeDriver" is-config="true" duration-ms="1249" started-at="2017-02-18T18:46:55Z" finished-at="2017-02-18T18:46:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method status="PASS" signature="closeAppiumServer()[pri:0, instance:com.Pcitc.AppAutomationTest.pagesHelper.TestInit@6e06451e]" name="closeAppiumServer" is-config="true" duration-ms="1" started-at="2017-02-18T18:47:01Z" finished-at="2017-02-18T18:47:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAppiumServer -->
      </class> <!-- com.Pcitc.AppAutomationTest.pagesHelper.TestInit -->
    </test> <!-- com.Pcitc.AppAutomationTest.pagesHelper.TestInit -->
  </suite> <!-- com.Pcitc.AppAutomationTest.pagesHelper.TestInit -->
</testng-results>
